apiVersion: v1
kind: Pod
metadata: 
  name: chatroom
  labels:
    app: chatroom
spec:
  containers:
  - name: nginx
    image: mynginx:latest
    imagePullPolicy: Never
    ports: 
    - name: nginx-port
      containerPort: 80
  - name: node
    image: mynode:latest
    imagePullPolicy: Never
    ports: 
    - name: node-port
      containerPort: 3000