apiVersion: v1
kind: Pod
metadata: 
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  containers:
  - name: phpmyadmin
    image: phpmyadmin:latest
    ports: 
    - name: phpmyadmin-port
      containerPort: 80
    env:
      # - name: PMA_ARBITRARY
      #   value: "1"
    - name: PMA_HOST
      value: mysql-server-service
    - name: PMA_USER
      value: "root"
    - name: PMA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: db-root-password